services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=5001
    networks:
      - app-network
    volumes:
      - ./uploads:/app/uploads:cached
      - ./backend:/app/backend:cached
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:5001/api/products"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://backend:5001
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    networks:
      - app-network
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy

networks:
  app-network:
    driver: bridge
